config/routes.rb
SampleApp::Application.routes.draw do  

  get "feedback/index"

  get "feedback/send_msg"

  get "search/index"
  get "messages/send_to"
  get "messages/compose"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", 
                                    registrations: "registrations", 
                                    :sessions => 'sessions' 
                                  }
                                  
  get "users/network", to: "users#network"
  resources :users do
    member do
      get :following, :followers, :compliments, :thankings, :notifications
      put :add_interest
    end
    collection do
      get :posts
      get :surpassed
      get :stacks
      get :about
      get :network_following
      get :network_followers
      get :profile_settings
      get :notification_settings
      get :user_settings
      get :settings
      get :notification
      get :message
      get :sort_network
      get :set_recipient
      get :popular_network
      get :services
      get :messages
      get :send_message
    end
  end
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'tags/:tag', to: 'statuses#index', as: :tag
  get 'tags/:tag', to: 'workouts#index', as: :tag
  get 'tags/:tag', to: 'services#index', as: :tag

  get "status_search_url" => "statuses#search_url", :as => 'status_search_url'
  put "/notifications/viewed" => "notifications#viewed"
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/search_goal', to: 'static_pages#search_goal'
  match '/search_more', to: 'static_pages#search_more'
  match '/connect', to: 'static_pages#connect'
  match '/interests', to: 'static_pages#interests'
  match '/follow', to: 'static_pages#follow'
  match '/notification',    to: 'users#notification'
  resources :services do
    collection do
      get "services/new"      
      get :share_modal    
    end
    
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
  end
  resources :posts do
    resources :votes
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
    collection do
      get :share_modal
    end
  end
  
  resources :compliments do
    collection do
      get :compliment_modal
    end
  end
  resources :stacks do
    member do
      post :follow
      put :unfollow
      post :like
      delete :unlike
      put :share
    end
    collection do
      get :popular
      get :following
      get :save_modal
      get :items
      get :comments
      get :share_modal
    end
  end
  resources :statuses do
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
    collection do
      get :share_modal
      get :mini_workout_modal
      post :mini_workout
    end
  end
  resources :groups
  resources :goals
  resources :workouts do
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
    collection do
      get :share_modal
    end
  end
  resources :exercises, only: [:destroy]
  resources :events
  resources :statuses, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :thankings, only: [:create]
  resources :feeds do
    member do
      post :like
      delete :unlike
    end
    collection do
      get :tags
      get :discover
      get :recommended
      get :popular
      get :featured
      get :filter_activity
      get :filter_discover
    end
  end
  resources :comments do
    member do
      post :like
      delete :unlike
    end
  end

  resources :after_signup
  
  root :to => "feeds#index", :constraints => lambda{ |req| req.session['warden.user.user.key'].present? }
  root :to => 'static_pages#home'

  get "/:id", :to => "users#show", :as => :user  
end

app/models/stack.rb
class Stack < ActiveRecord::Base
  include General, Shareable
  
  attr_accessible :description, :name, :likes_count, :stacked_items_attributes, 
                  :comments_count, :image_attributes, :shares

  belongs_to :user
  has_many :stacked_items, dependent: :destroy
  has_many :likes, dependent: :destroy, as: :likeable
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :notifications, as: :notifiable
  has_one :image, as: :imageable

  accepts_nested_attributes_for :stacked_items
  accepts_nested_attributes_for :image

  acts_as_followable
  acts_as_taggable_on :shares

  validates_presence_of :name

  def append_to_method
    id
  end

  def add_stacked_item_for(content)
    self.stacked_items.create!(
      stackable_id: content.id,
      stackable_type: content.type_name
      )
  end

  def content_image
    with_images = stacked_items.select { |i| i if i.stackable.images.present? }
    if with_images.count > 0
      with_images.first.stackable.images.first
    else
      false
    end
  end
end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController
  include Shared
  
  def index
    if signed_in?
      @user = current_user
      @following = @user.following_by_type('Stack').order(
                  "created_at DESC")
    else
      @popular = Stack.all.sort_by(&:followers_count).reverse
    end
  end

  ### Show Page Actions
  def show
    @stack = Stack.find(params[:id])
    @followers = @stack.followers.take(9)
    @items = @stack.stacked_items.order(
                "created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  def items
    @stack = Stack.find(params[:id])
    @items = @stack.stacked_items.order(
                "created_at DESC")
    respond_to do |format|
      format.js
    end
  end

  def comments
    @stack = Stack.find(params[:id])
    @comments = @stack.comments.order(
                "created_at DESC").paginate(page: params[:page]).per_page(4)
    respond_to do |format|
      if params[:page]
        format.js { render "comment-list" }
      else
        format.js
      end
    end
  end
  ### end show page actions

  def new
    @stack = current_user.stacks.new
  end

  def create
    @stack = current_user.stacks.build(params[:stack])
    if params[:from_modal]
      klass = params[:stack][:stacked_items_attributes][:"0"][:stackable_type].constantize
      @content = klass.find(params[:stack][:stacked_items_attributes][:"0"][:stackable_id])
    end
    respond_to do |format|
      if @stack.save
        @stack.user.follow(@stack)
        format.html { redirect_to @stack }
        format.js { render partial: "stacks/save_modal_success", locals: { stack: @stack } }
      else
        format.html { render :new }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
        format.js { render partial: "stacks/modal_new_error" }
      end
    end
  end

  def edit
    @stack = Stack.find(params[:id])
  end

  def update
    @stack = Stack.find(params[:id])

    if @stack.update_attributes(params[:stack])
      redirect_to @stack
    else
      render :edit
    end
  end

  def destroy
    @stack = Stack.find(params[:id])
    @stack.delete
    redirect_to stacks_path, notice: "Stack Deleted"
  end

  def save_modal
    klass = params[:c_type].constantize
    @content = klass.find(params[:c_id])
    respond_to do |format|
      format.js
    end
  end

  def popular
    @popular = Stack.all.sort_by(&:followers_count).reverse
  end

  def following
    @user = current_user
    @following = @user.following_by_type('Stack').order(
                "created_at DESC")
  end

  def follow
    @user = current_user
    @stack = Stack.find(params[:id])
    @user.follow(@stack)
    notify!(@stack, @stack.user, :follow_stack, :site, :email)
    respond_to do |format|
      format.js { render partial: "follow" }
    end
  end

  def unfollow
    @user = current_user
    @stack = Stack.find(params[:id])
    @user.stop_following(@stack)
    respond_to do |format|
      format.js { render partial: "follow" }
    end
  end

  def like
    @stack = Stack.find(params[:id])
    @like = @stack.likes.create!(:user_id => current_user.id)
    notify!(@like, @stack.user, :like_content, :site, :email)

    respond_to do |format|
      format.html { redirect_to @stack, notice: 'You liked this stack'}
      format.js { render partial: "like" }
    end
  end 

  # TODO: add notification fix
  def unlike
    @stack = Stack.find(params[:id])
    Stack.decrement_counter(:likes_count, @stack.id)
    @like = @stack.likes.where(:user_id => current_user.id).first
    @like.delete

    respond_to do |format|
      format.html { redirect_to @stack, notice: 'You unliked this stack'}
      format.js { render partial: "like" }
    end
  end
end

app/helpers/stacks_helper.rb
module StacksHelper
  def link_to_follow_stack(stack)
    if stack.followed_by?(current_user)
      link_to unfollow_stack_path(stack), method: :put, remote: true do
        content_tag(:i, '', class: "icon-reply") + "Unfollow"
      end
    else
      link_to follow_stack_path(stack), method: :post, remote: true do
        content_tag(:i, '', class: "icon-reply") + "Follow"
      end
    end
  end

  def link_to_like_stack(stack)
    if current_user.already_likes_this?(stack)
      link_to unlike_stack_path(stack), method: :delete, remote: true do
        content_tag(:i, '', class: "icon-heart") + ' ' + "Unlike"
      end
    else
      link_to like_stack_path(stack), method: :post, remote: true do
        content_tag(:i, '', class: "icon-heart") + ' ' + "Like"
      end
    end
  end

  def stack_owner_tools(stack, &block)
    block.call if current_user.owns(stack)
  end
end

app/views/stacks/_follow.js.erb
$(".follow_stack_<%= @stack.id %>").html("<%= j link_to_follow_stack(@stack) %>");

app/views/stacks/_form.html.haml
= simple_form_for @stack, :html => { multipart: true } do |f|
  = f.input :name, input_html: { class: "input-block-level" }
  = f.input :description, input_html: { class: "input-block-level", rows: 3 }

  - if @stack.image.present?
    = image_tag(@stack.image.item.url(:thumb, false))
    = f.simple_fields_for(:image) do |builder|
      = builder.label "Add Image"
      = builder.file_field :item
  - else
    = f.simple_fields_for(:image, @stack.build_image) do |builder|
      = builder.label "Add Image"
      = builder.file_field :item

  = f.submit "Save", class: "btn btn-warning"

app/views/stacks/_item.html.haml
%li.item.span4
  %section.box{class: item.stackable.css_name }
    %header
      .avatar
        = link_to item.stackable.user, {:rel => "tooltip", :data => { :placement => "right", :original_title => item.stackable.user.name}} do
          = profile_image_for(item.stackable.user, 34)
      / end .avatar
      = link_to item.stackable.user.name, item.stackable.user
      .timestamp
        = time_ago_in_words(item.stackable.created_at)
      / end .timestamp
    %h1= link_to item.stackable.feedable_title, item.stackable
    .media
      - if item.stackable.has_videos?
        - item.stackable.videos.each do |v|
          = render "shared/video_display", v: v, h: 200, w: 325
        %br
      - if item.stackable.has_images?
        - item.stackable.images.each do |i|
          = render "shared/image_display", i: i

      - if !item.stackable.feedable_title
        - if item.stackable.has_attached_link?
          = render 'statuses/status_attachment', status: item.stackable
    / end .media
    - if item.stackable.feedable_desc
      = simple_format h truncate(item.stackable.feedable_desc, length: 260)

    - if item.stackable.tags.present?
      - item.stackable.tags.map(&:name).map do |t|
        = link_to tags_feeds_path(tag: t), class: 'tag' do
          %i.icon-tag
          = t
      / end tags
    %footer
      = render '/shared/feed/social_stats', feed: item.stackable.feeds.first, content: item.stackable
      = render '/shared/feed/social_actions', feed: item.stackable.feeds.first, content: item.stackable

    / status comments
    = render '/shared/feed/comments_for_feed_item', feed: item.stackable.feeds.first, content: item.stackable
  / end .box.discussion

app/views/stacks/_modal_new_error.js.erb
$("#saveFade").hide();
$("#saveFade p#link-loading").hide();
$("#add_errors").show();
$("#add_errors ul").append("<li><%= @stack.errors.full_messages.to_sentence %></li>");

app/views/stacks/_save_modal_error.js.erb
$("#saveFade").hide();
$("#saveFade p#link-loading").hide();
$("#add_errors").show();
<% if blank == true %>
	$("#add_errors ul").append("<li>Please select a stack.</li>");
<% else %>
	<% @already.each do |e| %>
		$("#add_errors ul").append("<li><%= @content.type_name %> already saved to <%= e %>. Remove it to continue.</li>");
	<% end %>
<% end %>

app/views/stacks/_save_modal_success.js.erb
$("#saveFade #link-loading").hide();
$("#saveFade #success").show();
setTimeout(function() {
      $('#saveToStackModal').modal('hide')
}, 1000);

app/views/stacks/_save_to.html.haml
.row-fluid
  // Select stacks to save item to
  #add_errors.alert.alert-error{style: "display:none;"}
    %ul.unstyled
  = form_tag(eval("save_to_stacks_#{content.type_name.downcase}_path(content)"), method: :post, remote: true) do
    = select_tag :stacks, options_from_collection_for_select(current_user.stacks, "id", "name"), multiple: true, class: "block-level-input"
    %p= submit_tag "Add", class: "btn btn-warning submit_save"

  // OR create a new stack and save item to it
  - @stack = Stack.new
  = simple_form_for @stack, input_html: { multiplart: true }, remote: true do |f|
    %h4 Or create a new stack to save your #{content.type_name} to
    = f.input :name, label: false, placeholder: "Name", input_html: { class: "input-block-level" }
    = f.input :description, label: false, placeholder: "Descriptions", input_html: { class: "input-block-level", rows: 2 }
    = f.simple_fields_for :stacked_items, @stack.stacked_items.build do |i|
      = i.hidden_field :stackable_id, value: content.id
      = i.hidden_field :stackable_type, value: content.type_name
      = hidden_field_tag :from_modal, true
    = f.submit "Create and save", class: "btn btn-warning submit_save"

app/views/stacks/comment-list.js.erb
$('.comment_list').append('<%= j render(@comments) %>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@comments) %>');
  $(".pagination").css("display", "none")
<% else %>
  $(".pagination ul > li:last-child > a").attr("href", "")
  $("#more_stack_comments").attr("disabled", true)
<% end %>

app/views/stacks/comments.html.haml
= render 'shared/feed/filter', :locals => { :user => @user}
.container
  .row
    .span8
      %section#comments
        %h1 
          Comments
          %span.comments_count (#{@stack.comments_count})
        - if signed_in?
          = form_for current_user.comments.build, remote: true, html: { id: "comment_form"} do |c|
            = c.text_area :content, placeholder: "Type Something Here", rows: 2, class: "span6"
            = c.hidden_field :commentable_id, value: @stack.id
            = c.hidden_field :commentable_type, value: 'Stack'
            = c.submit "Post a comment", class: "btn btn-inverse btn-large pull-right"
            %p.social.pull-left
              %a.dev.google{ :href => "#" } Google
              %a.dev.facebook{ :href => "#" } Facebook
              %a.dev.twitter{ :href => "#" } Twitter
          / end #comment_form
        %ul.comment_list{class: "cl_#{@stack.id}"}
          = render @comments
        / end .comments_list
      
        = link_to "#", class: "btn btn-inverse btn-large", id: "more_stack_comments" do
          %i.icon-plus
          More
        = will_paginate @comments, id: "stack_show_pagination", style: "display:none"
      / end #comments

app/views/stacks/edit.html.haml
.container
  .row
    .span12
      = render "form"

app/views/stacks/following.html.haml
= render "shared/feed/filter"
/ %ol#feed_list.container
/   - @feed_items.each do |item|
/     = render_feed_item_for(item)        
/ / end #feed_list.container

%ol#feed_list.container
  = render @following, as: :stack

app/views/stacks/index.html.haml
.container
  #feed
    = render 'shared/feed/tabs'
    #tab-content
      - if signed_in?
        = render template: "stacks/following"
      - else
        = render template: "stacks/popular"
    
  / end #feed
/ end .container

app/views/stacks/items.html.haml
= render 'shared/feed/filter', :locals => { :user => @user}
%ol#feed_list.container
  = render partial: "item", as: :item, collection: @items
/ end #feed_list.container

app/views/stacks/popular.html.haml
= render "shared/feed/filter"

%ol#feed_list.container
  = render @popular, as: :stack