config/routes.rb
SampleApp::Application.routes.draw do  

  get "feedback/index"

  get "feedback/send_msg"

  get "search/index"
  get "messages/send_to"
  get "messages/compose"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", 
                                    registrations: "registrations", 
                                    :sessions => 'sessions' 
                                  }
                                  
  get "users/network", to: "users#network"
  resources :users do
    member do
      get :following, :followers, :compliments, :thankings, :notifications
      put :add_interest
    end
    collection do
      get :posts
      get :surpassed
      get :stacks
      get :about
      get :network_following
      get :network_followers
      get :profile_settings
      get :notification_settings
      get :user_settings
      get :settings
      get :notification
      get :message
      get :sort_network
      get :set_recipient
      get :popular_network
      get :services
      get :messages
      get :send_message
    end
  end
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'tags/:tag', to: 'statuses#index', as: :tag
  get 'tags/:tag', to: 'workouts#index', as: :tag
  get 'tags/:tag', to: 'services#index', as: :tag

  get "status_search_url" => "statuses#search_url", :as => 'status_search_url'
  put "/notifications/viewed" => "notifications#viewed"
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/search_goal', to: 'static_pages#search_goal'
  match '/search_more', to: 'static_pages#search_more'
  match '/connect', to: 'static_pages#connect'
  match '/interests', to: 'static_pages#interests'
  match '/follow', to: 'static_pages#follow'
  match '/notification',    to: 'users#notification'
  resources :services do
    collection do
      get "services/new"      
      get :share_modal    
    end
    
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
  end
  resources :posts do
    resources :votes
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
    collection do
      get :share_modal
    end
  end
  
  resources :compliments do
    collection do
      get :compliment_modal
    end
  end
  resources :stacks do
    member do
      post :follow
      put :unfollow
      post :like
      delete :unlike
      put :share
    end
    collection do
      get :popular
      get :following
      get :save_modal
      get :items
      get :comments
      get :share_modal
    end
  end
  resources :statuses do
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
    collection do
      get :share_modal
      get :mini_workout_modal
      post :mini_workout
    end
  end
  resources :groups
  resources :goals
  resources :workouts do
    member do
      post :like
      delete :unlike
      post :save_to_stacks
      put :share
    end
    collection do
      get :share_modal
    end
  end
  resources :exercises, only: [:destroy]
  resources :events
  resources :statuses, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :thankings, only: [:create]
  resources :feeds do
    member do
      post :like
      delete :unlike
    end
    collection do
      get :tags
      get :discover
      get :recommended
      get :popular
      get :featured
      get :filter_activity
      get :filter_discover
    end
  end
  resources :comments do
    member do
      post :like
      delete :unlike
    end
  end

  resources :after_signup
  
  root :to => "feeds#index", :constraints => lambda{ |req| req.session['warden.user.user.key'].present? }
  root :to => 'static_pages#home'

  get "/:id", :to => "users#show", :as => :user  
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  user_id     :integer
#

class Group < ActiveRecord::Base

	has_and_belongs_to_many :user

  attr_accessible :description, :name
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :description
  .form-actions
    = f.button :submit

app/views/groups/edit.html.haml
%h1 Editing group
= render 'form'
= link_to 'Show', @group
|
\#{link_to 'Back', groups_path}

app/views/groups/index.html.haml
.container-fluid
  .row-fluid
    .span2
      / Sidebar content
      .bs-docs-example
        %ul.nav.nav-pills.nav-stacked
          %li
            %a{:href => "/"}
              %i.icon-home
              Feed
          %li
            %a{:href => "workouts"}
              %i.icon-book
              Workouts
          %li
            %a{:href => "events"}
              %i.icon-calendar
              Events
          %li.active
            %a{:href => "groups"}
              %i.icon-user
              Groups
    .span6
      / Body content
      %section
      %section
        %h3 Groups
        %table
          %tr
            %th Name
            %th Description
            %th
            %th
            %th
          - @groups.each do |group|
            %tr
              %td= group.name
              %td= group.description
              %td= link_to 'Show', group
              %td= link_to 'Edit', edit_group_path(group)
              %td= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }
        %br/
    .span4
      %section.right-sidebar
        %p This is the recommended content

app/views/groups/new.html.haml
%h1 New group
= render 'form'
= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @group.name
%p
  %b Description:
  = @group.description
= link_to 'Edit', edit_group_path(@group)
|
\#{link_to 'Back', groups_path}